# -*- coding: utf-8 -*-
"""practice_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tPtME32w5um60DrWMLo02Xmx1efjMjI
"""

def square(a):
  return a*2
square(2)

def addition(a,b,c):
    d=a+b+c
    return d
addition(1,2,3)

def name(YourName):
  YourName = input(YourName)
  print("Your name is ", YourName)
name("YourName")

#for loop

for i in range(1,11):
  print(i)

for i in range(1,11):
  print("2 *",i,"=",i*2)

n="Hamza Alvi"
for i in n:
  print(i)

#constructor function

class student:
        def __init__(self,name,grade):
         self.name=name
         self.grade=grade
s = student("Hamza Alvi","A")
print("Name :",s.name)
print("Grade :",s.grade)

#while loop
i=0
while i<10:
  i= i+1
  if i%2==0:
    print(i)

i=0
while i<10:
  i=i+1
  print("5*",i,"=",i*5)

while True:
  i=input("Enter password :")
  if i=="admin123":
    print("password is correct")
    break
  else:
    print("password is incorrect")

#oop

class car:
  def __init__(self,brand,model,year):
    self.brand=brand
    self.model=model
    self.year=year
  def car_info(self):
    print(self.brand,self.model,self.year)
car1=car("Toyota","Corolla",2025)
car1.car_info()

class person:
  def __init__(self,name,age):
    self.name=name
    self.age=age
  def show_info(self):
    print(self.name,self.age)
class student(person):
  def __init__(self,name,age,grade):
    super().__init__(name,age)
    self.grade=grade
  def show_grade(self):
    print(self.grade)
student1= student("Hamza Alvi",20,"A")
student1.show_info()
student1.show_grade()

